name: 20 - DAST Scan Docker Image
on:
  workflow_dispatch:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true

  workflow_call:
    inputs:
      image-tag:
        type: string
        description: 'The name of the docker image to scan'
        required: true
env:
# used for docker
  REGISTRY: ghcr.io
  IMAGE_TAG: ${{ inputs.image-tag || github.event.inputs.image-tag }}

jobs:

  dast-scan:
      #contents: read # for actions/checkout to fetch code
      #security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      #actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status 
      #missing only package:read?
    name: DAST Scan
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker rm demoApp | true && docker run -d -p 80:80 --name demoApp ${{ env.IMAGE_TAG }}         

      - name: wait for container to start and create reports directory
        run: sleep 60 && mkdir reports
     
      - name: Run ZAP OWASP full scan
        uses: zaproxy/action-full-scan@v0.5.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost'
          cmd_options: | 
            -r reports/dvwa-report.html -J reports/dvwa-report.json -a -j -l WARN -z "-config auth.loginurl=http://localhost/login.php \
            -config auth.username="${{ secrets.USERNAME }}" \
            -config auth.password="${{ secrets.PASSWORD }}" \
            -config auth.username_field="username" \
            -config auth.password_field="password" \
            -config auth.submit_field="Login" \
            -config auth.exclude="http://localhost/logout.php,http://localhost/setup.php,http://localhost/security.php"
          allow_issue_writing: true
          
      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: DVWA_DAST_Report
          path: reports

      - name: stop docker
        if: always()
        run: |
          docker stop demoApp && docker rm demoApp && docker container prune --force && docker image prune --force
