name: 00 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

jobs:
  docker:
    name: Build docker image
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  dast-site:
    name: Scanning Website with DAST
    uses: ./.github/workflows/dast-site.yml
    secrets: inherit

  dast-docker:
    needs: [docker]
    name: Scanning Docker Image with DAST
    uses: ./.github/workflows/dast-docker.yml
    secrets: inherit
    variables: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}
 