name: 00 - Main CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:

jobs:
  docker:
    name: Build docker image
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  dast:
    needs: [docker]
    name: DAST Scan
    uses: ./.github/workflows/dast.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}
 